module.exports = {
  E0001: {
    errorDescription: "Invalid Input",
    statusCode: 400,
    message: "The provided input is invalid.",
    errorCode: "E0001",
  },
  E0002: {
    errorDescription: "Authentication Failed",
    statusCode: 401,
    message: "Invalid username or password.",
    errorCode: "E0002",
  },
  E0003: {
    errorDescription: "Resource Not Found",
    statusCode: 404,
    message: "The requested resource does not exist.",
    errorCode: "E0003",
  },
  E0004: {
    errorDescription: "Internal Server Error",
    statusCode: 500,
    message: "An unexpected error occurred. Please try again later.",
    errorCode: "E0004",
  },
  E0005: {
    errorDescription: "Missing User Type",
    statusCode: 400,
    message: "User Type is required for this operation.",
    errorCode: "E0005",
  },
  E0006: {
    errorDescription: "Operation Failure",
    statusCode: 400,
    message: "Sign up operation has failed.",
    errorCode: "E0006",
  },
  E0007: {
    errorDescription: "Missing Data",
    statusCode: 400,
    message: "Username or Userpassword is missing.",
    errorCode: "E0007",
  },
  E0008: {
    errorDescription: "Operation Failure",
    statusCode: 400,
    message: "Sign in operation has failed.",
    errorCode: "E0008",
  },
  E0009: {
    errorDescription: "Operation Failure",
    statusCode: 400,
    message: "Error Signing out.",
    errorCode: "E0009",
  },
  E0010: {
    errorDescription: "Operation Failure",
    statusCode: 400,
    message: "Error Getting User Data.",
    errorCode: "E0010",
  },
  E0011: {
    errorDescription: "No Data",
    statusCode: 400,
    message: "No Data for this User was found",
    errorCode: "E0011",
  },
  E0012: {
    errorDescription: "Update Failure",
    statusCode: 400,
    message: "Updating User Data has failed",
    errorCode: "E0012",
  },
  E0013: {
    errorDescription: "Missing Data",
    statusCode: 400,
    message: "PageIndex and PageSize are Mandatory",
    errorCode: "E0013",
  },
  E0014: {
    errorDescription: "Fetch Failure",
    statusCode: 400,
    message: "Fetching User Data has failed",
    errorCode: "E0014",
  },
  E0013: {
    errorDescription: "Missing Data",
    statusCode: 400,
    message: "UserStatus is Mandatory",
    errorCode: "E0015",
  },
  E0014: {
    errorDescription: "Review Failure",
    statusCode: 400,
    message: "Reviewing User has failed",
    errorCode: "E0016",
  },
  E0013: {
    errorDescription: "Missing Data",
    statusCode: 400,
    message: "UserId is Mandatory",
    errorCode: "E0017",
  },
  E0014: {
    errorDescription: "Review Failure",
    statusCode: 400,
    message: "Deleting User has failed",
    errorCode: "E0018",
  },
  E0019: {
    errorDescription: "Submit Failure",
    statusCode: 400,
    message: "Submitting an Application has failed",
    errorCode: "E0019",
  },
  E0020: {
    errorDescription: "Missing Data",
    statusCode: 400,
    message: "Username is Mandatory for this Operation",
    errorCode: "E0020",
  },
  E0021: {
    errorDescription: "Check Failure",
    statusCode: 400,
    message: "Checking username Availability failed",
    errorCode: "E0021",
  },
  E0022: {
    errorDescription: "Missing Data",
    statusCode: 400,
    message: "Username or Email is Mandatory for this Operation",
    errorCode: "E0022",
  },
  E0023: {
    errorDescription: "Check Failure",
    statusCode: 400,
    message: "Checking Application Status failed",
    errorCode: "E0023",
  },
  E0023: {
    errorDescription: "Missing Data",
    statusCode: 400,
    message: "PageIndex must be bigger than 0, PageSize must exist",
    errorCode: "E0023",
  },
  E0024: {
    errorDescription: "Fetch Failure",
    statusCode: 400,
    message: "Fetching Applications failed",
    errorCode: "E0024",
  },
  E0025: {
    errorDescription: "Missing Data",
    statusCode: 400,
    message: "Application ID is Missing or Invalid",
    errorCode: "E0025",
  },
  E0026: {
    errorDescription: "Fetch Failure",
    statusCode: 400,
    message: "Fetching Application Data failed",
    errorCode: "E0026",
  },
  E0027: {
    errorDescription: "Missing Data",
    statusCode: 400,
    message: "Application ID and Status are Mandatory",
    errorCode: "E0027",
  },
  E0028: {
    errorDescription: "Update Failure",
    statusCode: 400,
    message: "Updating Application Status failed",
    errorCode: "E0028",
  },
  E0029: {
    errorDescription: "Missing Data",
    statusCode: 400,
    message: "Email is Mandatory",
    errorCode: "E0029",
  },
  E0030: {
    errorDescription: "Reset Failure",
    statusCode: 400,
    message: "Requesting Reset Password failed",
    errorCode: "E0030",
  },
  E0031: {
    errorDescription: "Missing Data",
    statusCode: 400,
    message: "newPassword and resetToken are Mandatory",
    errorCode: "E0031",
  },
  E0032: {
    errorDescription: "Reset Failure",
    statusCode: 400,
    message: "Resetting Password failed",
    errorCode: "E0032",
  },
  E0033: {
    errorDescription: "Missing Data",
    statusCode: 400,
    message: "User ID is Mandatory",
    errorCode: "E0033",
  },
  E0034: {
    errorDescription: "Fetch Failure",
    statusCode: 400,
    message: "Fetching Retailer Details failed",
    errorCode: "E0034",
  },
  E0035: {
    errorDescription: "Missing Data",
    statusCode: 400,
    message: "retailerId, pageSize and pageIndex are Mandatory",
    errorCode: "E0035",
  },
  E0036: {
    errorDescription: "Fetch Failure",
    statusCode: 400,
    message: "Fetching Retailer Marketplace failed",
    errorCode: "E0036",
  },
  E0037: {
    errorDescription: "Missing Data",
    statusCode: 400,
    message:
      "(one of industryList, categoriesList), pageSize and pageIndex are Mandatory",
    errorCode: "E0037",
  },
  E0038: {
    errorDescription: "Missing Data",
    statusCode: 400,
    message: "searchTerm, pageSize and pageIndex are Mandatory",
    errorCode: "E0038",
  },
  E0039: {
    errorDescription: "No Data",
    statusCode: 400,
    message: "Search Yielded No Data",
    errorCode: "E0039",
  },
  E0040: {
    errorDescription: "Missing Data",
    statusCode: 400,
    message: "supplierId, pageSize and pageIndex are Mandatory",
    errorCode: "E0040",
  },
  E0041: {
    errorDescription: "Missing Data",
    statusCode: 400,
    message:
      "supplierId, retailerId, quotationDetails, supplierEstablishmentName, retailerEstablishmentName, shippingAddress are Mandatory",
    errorCode: "E0040",
  },
  E0042: {
    errorDescription: "Creation Failure",
    statusCode: 400,
    message: "Requesting Quotation has Failed",
    errorCode: "E0042",
  },
  E0043: {
    errorDescription: "Missing Data",
    statusCode: 400,
    message: "establishmentCommercialRegistrationNumber is Mandatory",
    errorCode: "E0043",
  },
  E0044: {
    errorDescription: "Check Failure",
    statusCode: 400,
    message: "Checking Commercial Reg. Number has Failed",
    errorCode: "E0044",
  },
  E0045: {
    errorDescription: "Missing Data",
    statusCode: 400,
    message: "retailerId, pageSize, pageIndex are Mandatory",
    errorCode: "E0045",
  },
  E0046: {
    errorDescription: "Fetch Failure",
    statusCode: 400,
    message: "Fetching Retailer Quotations has Failed",
    errorCode: "E0046",
  },
  E0047: {
    errorDescription: "Missing Data",
    statusCode: 400,
    message: "quotationId is Mandatory",
    errorCode: "E0047",
  },
  E0048: {
    errorDescription: "Fetch Failure",
    statusCode: 400,
    message: "Fetching Quotation Details has Failed",
    errorCode: "E0048",
  },
  E0049: {
    errorDescription: "Missing Data",
    statusCode: 400,
    message: "quotationId and quotationStatus are Mandatory",
    errorCode: "E0049",
  },
  E0050: {
    errorDescription: "Update Failure",
    statusCode: 400,
    message: "Updating Quotation Status has Failed",
    errorCode: "E0050",
  },
  E0051: {
    errorDescription: "Missing Data",
    statusCode: 400,
    message: "quotationId, buyerId, supplierId, paymentAmount are Mandatory",
    errorCode: "E0051",
  },
  E0052: {
    errorDescription: "Creation Failure",
    statusCode: 400,
    message: "Creating Purchase has Failed",
    errorCode: "E0052",
  },
  E0053: {
    errorDescription: "Missing Data",
    statusCode: 400,
    message: "supplierId, retailerId, rating and reviewComment are Mandatory",
    errorCode: "E0053",
  },
  E0054: {
    errorDescription: "Creation Failure",
    statusCode: 400,
    message: "Creating Review has Failed",
    errorCode: "E0054",
  },
  E0055: {
    errorDescription: "Missing Data",
    statusCode: 400,
    message: "retailerId, pageSize and pageIndex are Mandatory",
    errorCode: "E0055",
  },
  E0056: {
    errorDescription: "Fetch Failure",
    statusCode: 400,
    message: "Fetching Retailer Complaints has Failed",
    errorCode: "E0056",
  },
  E0057: {
    errorDescription: "Missing Data",
    statusCode: 400,
    message: "complaintId is Mandatory",
    errorCode: "E0057",
  },
  E0058: {
    errorDescription: "Fetch Failure",
    statusCode: 400,
    message: "Fetching Complaint Details has Failed",
    errorCode: "E0058",
  },
  E0059: {
    errorDescription: "Fetch Failure",
    statusCode: 400,
    message: "Fetching Quotation Actors has Failed",
    errorCode: "E0059",
  },
  E0060: {
    errorDescription: "Fetch Failure",
    statusCode: 400,
    message: "Fetching Complaint Types has Failed",
    errorCode: "E0060",
  },
  E0061: {
    errorDescription: "Missing Data",
    statusCode: 400,
    message:
      "complaintTitle, complaintTypeId,supplierId, retailerId, complaintNotes and quotationId are Mandatory",
    errorCode: "E0061",
  },
  E0062: {
    errorDescription: "Creation Failure",
    statusCode: 400,
    message: "Creating Complaint has Failed",
    errorCode: "E0062",
  },
  E0063: {
    errorDescription: "Missing Data",
    statusCode: 400,
    message: "userId, pageSize and pageIndex are Mandatory",
    errorCode: "E0063",
  },
  E0064: {
    errorDescription: "Fetch Failure",
    statusCode: 400,
    message: "Fetching Retailer Notifications has Failed",
    errorCode: "E0064",
  },
  TOKEN_EXPIRED: {
    errorDescription: "Authentication Failure",
    statusCode: 400,
    message: "token is expired.",
    errorCode: "TOKEN_EXPIRED",
  },
  TOKEN_MISSING: {
    errorDescription: "Authentication Failure",
    statusCode: 400,
    message: "token is missing.",
    errorCode: "TOKEN_MISSING",
  },
  DEFAULT_ERROR: {
    errorDescription: "Unknown Error",
    statusCode: 500,
    message: "An unknown error occurred.",
    errorCode: "9999",
  },
};
